settings : commit-msg 분기 로직 추가

diff --git a/.husky/commit-msg b/.husky/commit-msg
--- a/.husky/commit-msg
+++ b/.husky/commit-msg
@@ -1,1 +1,8 @@
-grep -E "^(feat|fix|docs|test|config|hotfix|dependency|settings) :" "$1"
+if grep -E "^(feat|fix|docs|test|config|hotfix|dependency|settings) :" "$1"; then
+        echo "Commit message format is correct."
+    else
+        echo "Error: Commit message format is incorrect."
+        echo "Please use the format: <type>: <description>"
+        echo "Where <type> is one of feat, fix, docs, test, config, hotfix, dependency, settings."
+        exit 1
+    fi
